### Find Shops
GET localhost:3000/shops

### Find Shop
GET localhost:3000/shops/1

### Save Shop
POST localhost:3000/shops
Content-Type: application/json

{ "name": "가게2", "address": "사평대로 353" }

### Find Menus without shop
GET localhost:3000/menus

### Find Menu without shop
GET localhost:3000/menus/2

### Find Menus
GET localhost:3000/shops/1/menus

### Find Menu
GET localhost:3000/shops/1/menus/2

### Save Menu
POST localhost:3000/shops/1/menus
Content-Type: application/json

{ "foodName": "가래떡떡볶이" }

### Get Orders
GET localhost:3000/orders

### Get Order
GET localhost:3000/orders/1

### Order
POST localhost:3000/orders
Content-Type: application/json

{
  "address": "시민로 209",
  "shopId": 1,
  "foodIds": [2, 4]
}

### Get Boss Orders
GET localhost:3000/boss/shops/1/orders


### Update Estimated time
PUT localhost:3000/boss/shops/1/orders/3
Content-Type: application/json

{
  "time": 5
}