### Find Shops
GET localhost:3000/shops

### Find Shop
GET localhost:3000/shops/1

### Save Shop
POST localhost:3000/shops
Content-Type: application/json

{ "name": "가게2", "address": "사평대로 353" }

### Find Menus
GET localhost:3000/shops/1/menus

### Find Menu
GET localhost:3000/shops/1/menus/2

### Save Menu
POST localhost:3000/shops/1/menus
Content-Type: application/json

{ "foodName": "떡볶이" }
